name: Clojure CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.lein
        key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-
    
    - name: Install Leiningen
      run: |
        curl -L https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
        chmod +x lein
        sudo mv lein /usr/local/bin/
    
    - name: Install clj-kondo
      run: |
        curl -sLO https://github.com/clj-kondo/clj-kondo/releases/latest/download/clj-kondo-linux-amd64.zip
        unzip clj-kondo-linux-amd64.zip
        sudo mv clj-kondo /usr/local/bin/
        chmod +x /usr/local/bin/clj-kondo
    
    - name: Run tests
      run: lein test
    
    - name: Run cljfmt check
      run: lein cljfmt check
      
    - name: Run kibit static analysis
      run: lein kibit
      
    - name: Run bikeshed code quality
      run: lein bikeshed --max-line-length 120
      
    - name: Run clj-kondo linting
      run: |
        clj-kondo --lint src test --config .clj-kondo/config.edn
      
    - name: Auto-format code (optional)
      run: lein cljfmt fix

  lint-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - uses: actions/checkout@v3
    - name: Generate lint report
      run: |
        echo "Linting completed successfully"